name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  build:
    strategy:
      matrix:
        go:
          - '1.19'
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: 'js/yarn.lock'
      - run: go generate ./...
      - name: Create Pull Request
        id: cpr
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update generated files
          base: ${{ github.head_ref }}
          branch: regenerate/${{ github.head_ref }}
          delete-branch: true
          title: "Regenerate files for ${{ github.head_ref }}"
          body: |
            Update generated files
          labels: |
            automated
          assignees: ${{ !contains(github.actor, '[bot]') && github.actor }}
          draft: false
      - name: Fail if there were changes
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Generated files don't match, pull request created:"
          echo "${{ steps.cpr.outputs.pull-request-url }}"
          exit 1
      - run: go test ./...
      - run: go build ./...
